influx.host=t63518.astra-honda.com
influx.port=8086
influx.username=influxadmin
influx.password=gAAAAABp4eg1NGe2bywwGYCc2sOH9BieCOHmXOdovGLb0RiK2aw_6Mxi27D4VCICb9kdfvTJyunMWn5S6xIb2UwpxUMgximg7w==
influx.database=AHMMO